name: CI
on:
  - push
permissions: {}
jobs:
  check-latest-versions:
    permissions:
      contents: read
    runs-on: [self-hosted, ubuntu-24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check latest versions
        run: ./check-latest-versions.sh
  build:
    permissions:
      contents: read
    name: build-${{ matrix.platform }}
    runs-on: ${{ matrix.os-label }}
    needs: check-latest-versions
    strategy:
      fail-fast: false
      matrix:
        include:
          - os-label: 'ubuntu-24.04'
            platform: 'linux-x64'
          - os-label: 'ubuntu-24.04'
            platform: 'linux-armv6'
          - os-label: 'ubuntu-24.04'
            platform: 'linuxmusl-x64'
          - os-label: 'ubuntu-24.04'
            platform: 'linux-ppc64le'
          - os-label: 'ubuntu-24.04'
            platform: 'linux-riscv64'
          - os-label: 'ubuntu-24.04'
            platform: 'linux-s390x'
          - os-label: 'ubuntu-24.04'
            platform: 'dev-wasm32'
          - os-label: 'ubuntu-24.04'
            platform: 'win32-ia32'
          - os-label: 'ubuntu-24.04'
            platform: 'win32-x64'
          - os-label: 'ubuntu-24.04'
            platform: 'win32-arm64v8'
          - os-label: 'macos-26'
            platform: 'darwin-arm64v8'
          - os-label: 'ubuntu-24.04-arm'
            platform: 'linux-arm64v8'
          - os-label: 'ubuntu-24.04-arm'
            platform: 'linuxmusl-arm64v8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pipx install meson
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        run: ./build.sh ${{ matrix.platform }}
      - name: Upload ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: '*.tar.gz'
          compression-level: 0
          retention-days: 1
          if-no-files-found: error
