name: CI
on:
  - push
  - workflow_dispatch
permissions: {}
jobs:
  build:
    permissions:
      contents: read
    name: build-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'linux-x64'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'linux-armv6'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'linuxmusl-x64'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'linux-ppc64le'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'linux-riscv64'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'linux-s390x'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'dev-wasm32'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'win32-ia32'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'win32-x64'
          - os: ['self-hosted', 'Linux', 'X64']
            platform: 'win32-arm64v8'
          - os: ['self-hosted', 'macOS', 'ARM64']
            platform: 'darwin-arm64v8'
          - os: ['self-hosted', 'Linux', 'ARM64']
            platform: 'linux-arm64v8'
          - os: ['self-hosted', 'Linux', 'ARM64']
            platform: 'linuxmusl-arm64v8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pipx install meson
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        run: ./build.sh ${{ matrix.platform }}
      - name: Upload ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: '*.tar.gz'
          compression-level: 0
          retention-days: 1
          if-no-files-found: error
